# docker-compose.yml

version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./public:/app/public

  db:
    image: mongo
    volumes:
      - mongo-data:/data/db  # Named volume for MongoDB data persistence
    ports:
      - "27017:27017"

  nginx:
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  mongo-data:

