# app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bestapp
  template:
    metadata:
      labels:
        app: bestapp
    spec:
      containers:
        - name: bestapp
          image: higard/bestapp:latest  # or replace with Docker Hub image
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017"

---
apiVersion: v1
kind: Service
metadata:
  name: bestapp
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: bestapp