name: Workflow for js app

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app
          push: true
          tags: khond/github:latest

      - name: Docker logout
        run: docker logout

      - name: Deployment our app
        env: 
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_PRIVATE_KEY: ${{ secrets.VM_PRIVATE_KEY }}
        run: |
          echo "$VM_PRIVATE_KEY" > /tmp/vm_private_key.pem
          chmod 400 /tmp/vm_private_key.pem

          ssh -o StrictHostKeychecking=no -i /tmp/vm_private_key.pem $VM_USER@$VM_HOST << EOF

          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/github:latest

          sudo docker run -d --name my-app ${{ secrets.DOCKERHUB_USERNAME }}/github:latest
          EOF
