name: Workflow for js app

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install all packeges
        run: sudo pip install boto boto3 ansible

      - name: Install anisble aws collection
        run: ansible-galaxy collection install amazon.aws

      - name: Run ansible playbook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ansible-playbook ./create_ec2.yml

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: create_ec2.yml
    # Optional, directory where playbooks live
          directory: ./
    # Optional, ansible configuration file content (ansible.cfg)
          configuration: |
            [defaults]
            callbacks_enabled = ansible.posix.profile_tasks, ansible.posix.timer
            stdout_callback = yaml
            nocows = false
    # Optional, SSH private key
    # key: ${{secrets.SSH_PRIVATE_KEY}}
    # Optional, literal inventory file contents
          inventory: |
            [all]
            localhost
    # Optional, SSH known hosts file content
    #known_hosts: |
            #example.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
    # Optional, encrypted vault password
    #     vault_password: ${{secrets.VAULT_PASSWORD}}
    # Optional, galaxy requirements filepath
    #     requirements: galaxy-requirements.yml
    # Optional, additional flags to pass to ansible-playbook
    #options: |
            #--inventory .hosts
            #--limit group1
            #--extra-vars hello=there
            #       --verbose

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app
          push: true
          tags: khond/github:latest

      - name: Docker logout
        run: docker logout

      - name: Deployment our app
        env: 
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_PRIVATE_KEY: ${{ secrets.VM_PRIVATE_KEY }}
        run: |
          echo "$VM_PRIVATE_KEY" > /tmp/vm_private_key.pem
          chmod 400 /tmp/vm_private_key.pem

          ssh -o StrictHostKeychecking=no -i /tmp/vm_private_key.pem $VM_USER@$VM_HOST << EOF
          sudo docker rm -f my-app || true 
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/github:latest 
          sudo docker run -d --name my-app -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/github:latest
          EOF

      - name: Cleaan up
        run: rm /tmp/vm_private_key.pem
