name: Workflow for js app

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install anisble aws collection
        run: ansible-galaxy collection install amazon.aws

      - name: Play Ansible Playbook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
        run: ansible-playbook -i localhost ./create_ec2.yml

      - name: Read public IP
        run: echo "PUBLIC_IP=$(cat ./public_ip.txt)" >> $GITHUB_ENV

      - name: Use public IP in next steps
        run: echo "The public IP of the deployed EC2 instance is ${{ env.PUBLIC_IP }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app
          push: true
          tags: khond/github:latest

      - name: Docker logout
        run: docker logout

      - name: Deployment our app
        env: 
          VM_HOST: ${{ env.PUBLIC_IP }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_PRIVATE_KEY: ${{ secrets.VM_PRIVATE_KEY }}
        run: |
          echo "$VM_PRIVATE_KEY" > /tmp/vm_private_key.pem
          chmod 400 /tmp/vm_private_key.pem

          ssh -o StrictHostKeychecking=no -i /tmp/vm_private_key.pem $VM_USER@$VM_HOST << EOF
          sudo docker rm -f my-app || true 
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/github:latest 
          sudo docker run -d --name my-app -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/github:latest
          EOF

      - name: Cleaan up
        run: rm /tmp/vm_private_key.pem
