name: Workflow for js app

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build js app
        run: |
          cd ..
          pwd
          ls -la
          cd app
          docker build -t js_app:1.0.0 .
