name: Workflow for js app

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install all packeges
        run: sudo pip install boto boto3 ansible

      - name: Install anisble aws collection
        run: ansible-galaxy collection install amazon.aws

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: create_ec2.yml
          configuration: |
            [defaults]
            callbacks_enabled = ansible.posix.profile_tasks, ansible.posix.timer
            stdout_callback = yaml
            nocows = false
          inventory: |
            [all]
            localhost

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app
          push: true
          tags: khond/github:latest

      - name: Docker logout
        run: docker logout

      - name: Deployment our app
        env: 
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_PRIVATE_KEY: ${{ secrets.VM_PRIVATE_KEY }}
        run: |
          echo "$VM_PRIVATE_KEY" > /tmp/vm_private_key.pem
          chmod 400 /tmp/vm_private_key.pem

          ssh -o StrictHostKeychecking=no -i /tmp/vm_private_key.pem $VM_USER@$VM_HOST << EOF
          sudo docker rm -f my-app || true 
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/github:latest 
          sudo docker run -d --name my-app -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/github:latest
          EOF

      - name: Cleaan up
        run: rm /tmp/vm_private_key.pem
